id: I01817428
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:36:24+00:00'
last_modified: '2022-06-07T21:01:29.872464+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12075
  title: བཀའ་བརྒྱད་བདེ་གཤེགས་འདུས་པའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DE9C:
      image_group_id: I1KG13721
      title: ''
      total_pages: 662
      order: 1
      base_file: DE9C.txt
    D1C3:
      image_group_id: I1KG13722
      title: ''
      total_pages: 694
      order: 2
      base_file: D1C3.txt
    A556:
      image_group_id: I1KG13723
      title: ''
      total_pages: 660
      order: 3
      base_file: A556.txt
    036B:
      image_group_id: I1KG13724
      title: ''
      total_pages: 690
      order: 4
      base_file: 036B.txt
    4B0D:
      image_group_id: I1KG13725
      title: ''
      total_pages: 622
      order: 5
      base_file: 4B0D.txt
    F9DB:
      image_group_id: I1KG13726
      title: ''
      total_pages: 655
      order: 6
      base_file: F9DB.txt
    A441:
      image_group_id: I1KG13727
      title: ''
      total_pages: 710
      order: 7
      base_file: A441.txt
    FC8B:
      image_group_id: I1KG13728
      title: ''
      total_pages: 510
      order: 8
      base_file: FC8B.txt
    478A:
      image_group_id: I1KG13729
      title: ''
      total_pages: 682
      order: 9
      base_file: 478A.txt
    '8436':
      image_group_id: I1KG13730
      title: ''
      total_pages: 654
      order: 10
      base_file: 8436.txt
    FF64:
      image_group_id: I1KG13731
      title: ''
      total_pages: 693
      order: 11
      base_file: FF64.txt
    DBC9:
      image_group_id: I1KG13732
      title: ''
      total_pages: 656
      order: 12
      base_file: DBC9.txt
    '1197':
      image_group_id: I1KG13733
      title: ''
      total_pages: 704
      order: 13
      base_file: 1197.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
